import { Router, type Request, type Response } from 'express';
import { FieldValue } from 'firebase-admin/firestore';
import { requireAuth } from '../middleware/auth.js';
import { XadTagConflictError, xadTagRepository } from '../repositories/xadtagRepository.js';
import { adminDb } from '../services/firebaseAdmin.js';
import { broadcastRemoval, broadcastTenant } from '../services/positionBroadcast.js';
import { traccarRealtimeService } from '../services/traccarRealtimeService.js';
import { xadTagService } from '../services/xadtagService.js';
import { buildTraccarDeviceName, normalizeXadTagIdentifier, originalXadTagIdentifier } from '../domain/xadtag.js';

export const xadTagsRouter = Router();
xadTagsRouter.use(requireAuth);
const tenant = (req: Request) => { if (!req.tenantId || req.tenantId === 'admin' || req.tenantId === '__apex__') throw new Error('Tenant inválido.'); return req.tenantId; };
const fail = (res: Response, error: unknown) => {
  const message = error instanceof Error ? error.message : 'Falha na integração Traccar.';
  return res.status(error instanceof XadTagConflictError ? 409 : /não encontrad|inválid|Informe|ultrapassar/i.test(message) ? 400 : 502).json({ ok: false, error: message });
};

xadTagsRouter.post('/', async (req, res) => { try { const tid = tenant(req); const result = await xadTagService.register(tid, tid, req.body?.imei, req.body?.description); await xadTagRepository.audit(tid, req.authUser!.uid, 'xadtag.created', result.item.id, result.created ? 'created' : 'existing'); await traccarRealtimeService.refreshMapping(); res.status(result.created ? 201 : 200).json({ ok: true, data: result.item, created: result.created }); } catch (error) { fail(res, error); } });
xadTagsRouter.get('/', async (req, res) => { try { res.json({ ok: true, data: await xadTagRepository.list(tenant(req)) }); } catch (error) { fail(res, error); } });
xadTagsRouter.get('/:id', async (req, res) => { try { const item = await xadTagRepository.get(tenant(req), req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'XADTAG não encontrada.' }); res.json({ ok: true, data: item }); } catch (error) { fail(res, error); } });
xadTagsRouter.post('/:id/check', async (req, res) => { try { const tid = tenant(req); const item = await xadTagRepository.get(tid, req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'XADTAG não encontrada.' }); const result = await xadTagService.check(item); await xadTagRepository.audit(tid, req.authUser!.uid, 'xadtag.checked', item.id, 'success'); res.json({ ok: true, data: result }); } catch (error) { fail(res, error); } });
xadTagsRouter.post('/:id/link', async (req, res) => { try { const tid = tenant(req); const item = await xadTagRepository.get(tid, req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'XADTAG não encontrada.' }); const entityId = String(req.body?.entityId || ''); if (!entityId) return res.status(400).json({ ok: false, error: 'Informe o veículo/ativo.' }); const vehicleRef = adminDb.doc(`tenants/${tid}/vehicles/${entityId}`); const vehicle = await vehicleRef.get(); if (!vehicle.exists) return res.status(404).json({ ok: false, error: 'Veículo/ativo não encontrado.' }); const linkedEntityName = String(req.body?.entityName || vehicle.get('model') || entityId); await adminDb.runTransaction(async tx => { tx.update(vehicleRef, { tagId: item.id, updatedAt: Date.now() }); tx.update(adminDb.doc(`tenants/${tid}/tags/${item.id}`), { linkedEntityId: entityId, linkedEntityName, updatedAt: Date.now() }); }); item.linkedEntityId = entityId; item.linkedEntityName = linkedEntityName; try { await xadTagService.check(item); } catch { /* vínculo continua com último snapshot */ } await xadTagRepository.audit(tid, req.authUser!.uid, 'xadtag.linked', item.id, 'success'); const fresh = await xadTagRepository.get(tid, item.id); if (fresh) { const marker = xadTagService.toLiveMap(fresh); if (marker) broadcastTenant(tid, { type: 'position', data: marker }); } res.json({ ok: true, data: fresh }); } catch (error) { fail(res, error); } });
xadTagsRouter.post('/:id/unlink', async (req, res) => { try { const tid = tenant(req); const item = await xadTagRepository.get(tid, req.params.id); if (!item) return res.status(404).json({ ok: false, error: 'XADTAG não encontrada.' }); await adminDb.runTransaction(async tx => { if (item.linkedEntityId) tx.update(adminDb.doc(`tenants/${tid}/vehicles/${item.linkedEntityId}`), { tagId: FieldValue.delete(), updatedAt: Date.now() }); tx.update(adminDb.doc(`tenants/${tid}/tags/${item.id}`), { linkedEntityId: FieldValue.delete(), linkedEntityName: FieldValue.delete(), updatedAt: Date.now() }); }); broadcastRemoval(tid, `xadtag_${item.identifierNormalized}`); await xadTagRepository.audit(tid, req.authUser!.uid, 'xadtag.unlinked', item.id, 'success'); res.json({ ok: true }); } catch (error) { fail(res, error); } });

xadTagsRouter.post('/import/preview', async (req, res) => { try { const tid = tenant(req); const rows = Array.isArray(req.body?.rows) ? req.body.rows.slice(0, 1000) : []; const data = await Promise.all(rows.map(async (row: Record<string, unknown>, index: number) => { try { const imeiOriginal = originalXadTagIdentifier(String(row.imei ?? row['Serial/IMEI'] ?? '')); const identifierNormalized = normalizeXadTagIdentifier(imeiOriginal); const existing = await xadTagRepository.findByIdentifier(tid, identifierNormalized); return { index, imeiOriginal, identifierNormalized, traccarDeviceName: buildTraccarDeviceName(tid, imeiOriginal), status: existing ? 'existing' : 'ready' }; } catch (error) { return { index, imeiOriginal: String(row.imei || ''), status: 'invalid', error: (error as Error).message }; } })); res.json({ ok: true, data }); } catch (error) { fail(res, error); } });
xadTagsRouter.post('/import/commit', async (req, res) => { try { const tid = tenant(req); const rows = Array.isArray(req.body?.rows) ? req.body.rows.slice(0, 1000) : []; const results: Array<Record<string, unknown>> = []; let cursor = 0; const workers = Array.from({ length: Math.min(5, rows.length) }, async () => { while (cursor < rows.length) { const index = cursor++; const row = rows[index]; try { const result = await xadTagService.register(tid, tid, String(row.imei ?? row['Serial/IMEI'] ?? ''), String(row.description ?? row.descricao ?? '')); results[index] = { index, status: result.created ? 'created' : 'existing', id: result.item.id }; } catch (error) { results[index] = { index, status: error instanceof XadTagConflictError ? 'unavailable' : 'invalid', error: (error as Error).message }; } } }); await Promise.all(workers); const summary = { total: rows.length, created: results.filter(r => r.status === 'created').length, existing: results.filter(r => r.status === 'existing').length, invalid: results.filter(r => r.status === 'invalid').length, unavailable: results.filter(r => r.status === 'unavailable').length }; await xadTagRepository.audit(tid, req.authUser!.uid, 'xadtag.imported', null, JSON.stringify(summary)); await traccarRealtimeService.refreshMapping(); console.info(JSON.stringify({ event: 'traccar.import.completed', tenantId: tid, ...summary })); res.json({ ok: true, data: { ...summary, rows: results } }); } catch (error) { fail(res, error); } });

export const liveMapRouter = Router();
liveMapRouter.use(requireAuth);
liveMapRouter.get('/', async (req, res) => { try { const data = (await xadTagRepository.list(tenant(req))).map(item => xadTagService.toLiveMap(item)).filter(Boolean); res.json({ ok: true, data }); } catch (error) { fail(res, error); } });
